FROM python:3.12-slim AS builderr
WORKDIR /app
COPY requirements.txt .
RUN pip install --prefix=/install --no-cache-dir -r requirements.txt
COPY . .

FROM python:3.12-slim
COPY --from=builderr /install /usr/local
COPY --from=builderr /app /app
WORKDIR /app
ENV PYTHONPATH=/usr/local/lib/python3.12/site-packages
CMD ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
